### ISSUE TITLE
Classical Chinese name

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/highlight#1]
Just have a look at the org

![image](https://user-images.githubusercontent.com/11247099/72197878-545bdd00-3461-11ea-849a-31a163890372.png)

I think it's good to have a Chinese name for highlight as well! (and maybe every repo in the future XD)

Something like `四色套印` `套印版畫` just came to my mind.

**Comment by LingDong-** [comment]
Dunno, perhaps `文言五色`? We can put something and change it when we think of a better name.
